# Generated by Django 5.0.6 on 2024-07-15 03:46

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('Key', models.CharField(blank=True, max_length=100, null=True)),
                ('DateCreated', models.DateTimeField(auto_now_add=True, null=True)),
                ('AccType', models.CharField(blank=True, max_length=50, null=True)),
                ('Username', models.CharField(max_length=100, unique=True)),
                ('Name', models.CharField(blank=True, max_length=100, null=True)),
                ('ProfilePic', models.ImageField(blank=True, default='add-image.gif', null=True, upload_to='')),
                ('is_superuser', models.BooleanField(default=False)),
                ('is_admin', models.BooleanField(default=False)),
                ('is_staff', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=False)),
                ('RawPassword', models.CharField(blank=True, max_length=50, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='SavedFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('DateCreated', models.DateTimeField(auto_now_add=True)),
                ('File', models.FileField(upload_to='saved_file/')),
            ],
        ),
        migrations.CreateModel(
            name='Admin',
            fields=[
                ('account_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
            bases=('src.account',),
        ),
        migrations.CreateModel(
            name='Client',
            fields=[
                ('account_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('Email', models.EmailField(blank=True, max_length=254, null=True, unique=True)),
                ('DateRegister', models.DateTimeField(default=django.utils.timezone.now)),
                ('Address', models.CharField(blank=True, max_length=200, null=True)),
                ('PhoneNum', models.CharField(blank=True, max_length=13, null=True)),
                ('DOB', models.DateField(blank=True, null=True)),
            ],
            options={
                'abstract': False,
            },
            bases=('src.account',),
        ),
        migrations.CreateModel(
            name='UploadedFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('DateCreated', models.DateTimeField(auto_now_add=True)),
                ('FileName', models.CharField(max_length=255)),
                ('SavedFileName', models.CharField(max_length=255)),
                ('File', models.FileField(upload_to='temp/')),
                ('User', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='UserActivity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('DateCreated', models.DateTimeField(auto_now_add=True)),
                ('Activity', models.CharField(max_length=500)),
                ('Link', models.CharField(blank=True, max_length=500, null=True)),
                ('User', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Title', models.CharField(max_length=200)),
                ('Description', models.TextField(blank=True, null=True)),
                ('Created', models.DateTimeField(auto_now_add=True)),
                ('Duedate', models.DateTimeField(blank=True, null=True)),
                ('LastChange', models.DateTimeField(auto_now=True)),
                ('Photo', models.ImageField(blank=True, null=True, upload_to='images/')),
                ('Document', models.FileField(blank=True, null=True, upload_to='documents/')),
                ('Complete', models.BooleanField(default=False)),
                ('Client', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='src.client')),
            ],
            options={
                'ordering': ['Complete', 'Duedate'],
            },
        ),
    ]
