# Generated by Django 5.0.6 on 2024-07-15 07:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('src', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='task',
            old_name='Client',
            new_name='client',
        ),
    ]
