# Generated by Django 5.0.6 on 2024-07-15 07:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('src', '0002_rename_client_task_client'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='task',
            options={'ordering': ['complete', 'duedate']},
        ),
        migrations.RenameField(
            model_name='task',
            old_name='Complete',
            new_name='complete',
        ),
        migrations.RenameField(
            model_name='task',
            old_name='Created',
            new_name='created',
        ),
        migrations.RenameField(
            model_name='task',
            old_name='Description',
            new_name='description',
        ),
        migrations.RenameField(
            model_name='task',
            old_name='Document',
            new_name='document',
        ),
        migrations.RenameField(
            model_name='task',
            old_name='Duedate',
            new_name='duedate',
        ),
        migrations.RenameField(
            model_name='task',
            old_name='LastChange',
            new_name='lastchange',
        ),
        migrations.RenameField(
            model_name='task',
            old_name='Photo',
            new_name='photo',
        ),
        migrations.RenameField(
            model_name='task',
            old_name='Title',
            new_name='title',
        ),
    ]
