# Generated by Django 5.0.6 on 2024-07-16 02:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('src', '0003_alter_task_options_rename_complete_task_complete_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='task',
            options={'ordering': ['complete', 'duedate', '-created']},
        ),
    ]
