# Generated by Django 5.0.6 on 2024-07-17 04:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('src', '0004_alter_task_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='task',
            options={'ordering': ['complete', 'duedate', '-lastchange']},
        ),
    ]
