# Generated by Django 5.0.6 on 2024-06-25 02:56

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_user_address_user_avatar_user_date_register_user_dob_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='dob',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='user',
            name='name',
            field=models.CharField(default='user', max_length=50),
        ),
        migrations.AlterField(
            model_name='user',
            name='phoneno',
            field=models.CharField(default='xxxxxxxxxxx', max_length=11),
        ),
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(blank=True, max_length=150, null=True, unique=True),
        ),
    ]
